version: '3.3'

services:
  db:   # nome do container do MariaDD
    image: mysql:5.7 # semelhante ao FROM do Dockerfile
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: junior
      MYSQL_PASSWORD: secret

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80" #1ºporta do host:2º porta da imagem
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: junior
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}

